### ISSUE TITLE
mac上，运行命令后，访问显示IP的网站并未显示我的vps的公网ip

### ISSUE THREAD

**Issue by briteming** [net-byte/vtun#15]
hi.

on my mac:
yudeMacBook-Air:~ ym$ sudo vtun -k mykey -l 127.0.0.1:3000 -mtu 1200 -p tcp -s vps-public-ip:3001
显示：
2022/04/30 23:14:18 init config:{"LocalAddr":"127.0.0.1:3000","ServerAddr":"vps-public-ip:3001","CIDR":"172.16.0.10/24","Key":"mykey","Protocol":"tcp","DNS":"8.8.8.8:53","WebSocketPath":"/freedom","ServerMode":false,"GlobalMode":false,"Obfs":false,"MTU":1200,"Timeout":30}
2022/04/30 23:14:18 vtun tcp client started on 127.0.0.1:3000
2022/04/30 23:14:18 interface created: utun2
2022/04/30 23:14:18 exec cmd: ifconfig [utun2 inet 172.16.0.10 172.16.0.1 up]:
2022/04/30 23:14:18 physical interface en0 gateway 192.168.1.1 network 192.168.1.0/24
2022/04/30 23:14:18 exec cmd: route [add default 192.168.1.1]:
route: writing to routing socket: File exists
add net default: gateway 192.168.1.1: File exists
2022/04/30 23:14:18 exec cmd: route [change default 192.168.1.1]:
change net default: gateway 192.168.1.1

然后，在浏览器里访问显示IP的网站，并未显示我的vps的公网ip，而是我的isp分配给我的ip,  所以并不能用此vpn翻wall.
该怎么解决？

**Comment by net-byte** [comment]
客户端需要开启全局模式，添加-g参数
