### ISSUE TITLE
how to compile using macos

### ISSUE THREAD

**Issue by tormentous** [net-byte/vtun#21]
as the title says.

**Comment by net-byte** [comment]
#Mac amd64
CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o ./bin/vtun-darwin-amd64 ./main.go
#Mac arm64
CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o ./bin/vtun-darwin-arm64 ./main.go
