### ISSUE TITLE
win7下 先删除0.0.0.0 网关。 。 后执行添加虚拟网卡的网关。 这个命令怎么也不执行，没有错误提示但是路由里面就是没有

### ISSUE THREAD

**Issue by getecms** [net-byte/vtun#36]
win7下 先删除0.0.0.0 网关。 。 后执行添加虚拟网卡的网关。 这个命令怎么也不执行，没有错误提示但是路由里面就是没有，不知道怎么回事。 。 

netutil.ExecCmd("cmd", "/C", "route", "add", "0.0.0.0", "mask", "0.0.0.0", gateway, "metric", "6")

这一条就没反应一直。 。 大神给分析分析

**Comment by net-byte** [comment]
我没有win7测试，你能在cmd中手动敲命令试试
