### ISSUE TITLE
udp模式完全不可用，ws模式运行正常

### ISSUE THREAD

**Issue by vip123456789** [net-byte/vtun#38]

**Comment by net-byte** [comment]
我这边测试可用，参数是否设置正确？端口是否开启？

**Comment by vip123456789** [comment]
服务端vtun -S -l :3001 -c 172.16.0.1/24 -k 123456
客户端vtun -l :3000 -s server-addr:3001 -c 172.16.0.10/24 -k 123456
强制加了-p udp也一样不行。
希望能添加-v日志功能，方便排查一些问题
