### ISSUE TITLE
希望可以支持自签证书

### ISSUE THREAD

**Issue by vip123456789** [net-byte/vtun#39]
你好，希望vtun可以支持自签证书，谢谢。
https://github.com/FiloSottile/mkcert

**Comment by net-byte** [comment]
vtun支持自签证书，设置参数-certificate和-privatekey

**Comment by vip123456789** [comment]
我用上面的工具生成证书测试时提示不可用。x509: certificate signed by unknown authority

**Comment by vip123456789** [comment]
没仔细看，加了-isv参数后，问题解决了
