### ISSUE TITLE
[Question] About the parameters

### ISSUE THREAD

**Issue by Handsome1080P** [net-byte/vtun#41]
Which parameters need set at Client side and which parameters need set at Server side,pls show more details in help.Then,the program already set a tun device at Client side why still need listen a local address:port?

**Comment by net-byte** [comment]
Only UDP client need listen a local address,I will do some optimization for code.

**Comment by Handsome1080P** [comment]
>
this is a VPN tools not tunnel right?why need listen a local address: port at Client side,just tun is enough.
