### ISSUE TITLE
UDP 模式不稳定，建议不要作为默认值

### ISSUE THREAD

**Issue by wanglong001** [net-byte/vtun#44]
![image](https://user-images.githubusercontent.com/14817376/200275995-78172948-de07-4845-a31a-49f6fde9d078.png)

对于application/octet-stream 类型非常不友好， 丢包一直重发，效率很低

![image](https://user-images.githubusercontent.com/14817376/200276506-29221d98-5078-4975-bb81-0a6e7b6bf3f1.png)

**Comment by net-byte** [comment]
Openvpn和Wireguard也用udp协议，所以VPN默认还是选择了udp协议。
