### ISSUE TITLE
客户端可以ping服务端，但是客户端之间无法ping通，请问如何解决，谢谢

### ISSUE THREAD

**Issue by hkhk366** [net-byte/vtun#47]
Linux Docker服务端
docker run  -d --privileged --restart=always --net=host --name vtun-server netbyte/vtun -S -l :3001 -c 10.1.0.1/24 -k xxx

Windows客户端1号：
vtun.exe  -s v1.cognsoft.com:3001 -c 10.1.0.2/24 -k xxx

Windows客户端2号：
vtun.exe  -s v1.cognsoft.com:3001 -c 10.1.0.3/24 -k xxx

这样运行后，客户端1号和2号都能成功的ping服务端10.1.0.1，但是客户端1号10.1.0.2和客户端2号10.1.0.3则无法互相ping通，请问应该如何解决？谢谢

**Comment by net-byte** [comment]
不支持客户端之间互通，只支持客户端与服务端互通。
