### ISSUE TITLE
服务端无法ping通客户端，只有客户端ping了服务端之后才能从服务端ping通客户端为何？

### ISSUE THREAD

**Issue by lixuedong-edu** [net-byte/vtun#48]
初始服务端无法ping通客户端，只有客户端ping了服务端之后才能从服务端ping通客户端，而且客户端停止ping之后服务端过5分钟后也无法ping通客户端。

**Comment by net-byte** [comment]
因为请求需要客户端发起，建立连接后双方可以ping通。如果连接长时间没有数据流通，连接会断，服务器缓存的客户端连接被清除。

**Comment by lixuedong-edu** [comment]
嗯，我的使用场景用服务器连客户端比较多有办法可以保持连接不断开吗？

**Comment by net-byte** [comment]
> 嗯，我的使用场景用服务器连客户端比较多有办法可以保持连接不断开吗？

websocket协议支持心跳包，我可以试试加入发心跳包来使连接保活。

**Comment by lixuedong-edu** [comment]
好的，发布新版我可以测试看下
