### ISSUE TITLE
[FeatureRequest]More detail QUIC and KCP Parameters Settings

### ISSUE THREAD

**Issue by Handsome1080P** [net-byte/vtun#55]
I just now know this project added QUIC and KCP.Great.But seems not support custom the detail settings.In another hand,can remove the client listening？Thx.

**Comment by net-byte** [comment]
What parameters do you want to add?

**Comment by Handsome1080P** [comment]
> What parameters do you want to add?

For KCP: `https://github.com/skywind3000/kcp/blob/master/README.en.md#protocol-configuration`
For QUIC: the ｅncryption and certificates
