### ISSUE TITLE
源码中关于route的设置128.0.0.0是不是写错了

### ISSUE THREAD

**Issue by yl604636754** [net-byte/vtun#58]
tun.go中
netutil.ExecCmd("route", "add", "default", config.ServerIP)
					netutil.ExecCmd("route", "change", "default", config.ServerIP)
					netutil.ExecCmd("route", "add", "0.0.0.0/1", "-interface", iface.Name())
					netutil.ExecCmd("route", "add", "128.0.0.0/1", "-interface", iface.Name())
128.0.0.0/1是不是应该127.0.0.1着急写错了？

**Comment by vip123456789** [comment]
没有错，0.0.0.0/1 + 128.0.0.0/1 = 0.0.0.0/0，一些vpn软件全局代理上网都是这么写。把一条拆分为2条这样写，退出时自动删除路由表的时候不会改动原来的0.0.0.0/0，更便利。相关资料，你可以阅读一下这两个https://sourceforge.net/p/openvpn/mailman/message/26047632/
https://git.zx2c4.com/wireguard-windows/about/docs/netquirk.md

**Comment by yl604636754** [comment]
> 没有错，0.0.0.0/1 + 128.0.0.0/1 = 0.0.0.0/0，一些vpn软件全局代理上网都是这么写。把一条拆分为2条这样写，退出时自动删除路由表的时候不会改动原来的0.0.0.0/0，更便利。相关资料，你可以阅读一下这两个https://sourceforge.net/p/openvpn/mailman/message/26047632/ https://git.zx2c4.com/wireguard-windows/about/docs/netquirk.md

非常感谢
