### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by hinego** [net-byte/vtun#6]
我用的ubuntu18测试，客户端 ping 服务端可以成功 但是

始终没办法连上公网？
这是server端的

```
root@ubuntu:~# iptables -t nat -L -n
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  172.16.0.0/24        0.0.0.0/0
```

client端 非global模式（global时所有路由都走tun0了 连服务端都连不上）

`root@ubuntu:~# curl --interface tun0 ip.sb
`
无任何相应

对软件做了输出

服务端有收到客户端的请求 但是没有进行响应（ping的时候不但有请求 也有相应）

**Comment by net-byte** [comment]
可能流量转发到公网网卡配置有问题，配置如下：
sudo echo 1 > /proc/sys/net/ipv4/ip_forward
sudo sysctl -p
sudo iptables -t nat -A POSTROUTING -s 172.16.0.0/24 -o ensx -j MASQUERADE
注意：ensx　用你能上公网的网卡名称

**Comment by hinego** [comment]
步骤都没错的 今天用mac作为客户端测试成功了

之前服务端客户端都是linux（ubuntu18）客户端死都不通

要么非全局可以ping通 服务端

全局时直接完全没网络

请问你测试过linux作为客户端吗

**Comment by net-byte** [comment]
全局模式有一些匹配规则，可能没找到对应的网卡。我ubuntu 20.04测试没问题，你能执行一下ifconfig命令吗?把网卡信息贴一下，方便排查。

**Comment by JayKuin** [comment]
我遇到了相同的问题，配置都是一样的，经过抓包查看，发现服务器端收到了客户端的流量，但是服务器端将UDP载荷写入tun后数据包消失，而不是预想的通过ens33网卡发送出去

**Comment by net-byte** [comment]
> 我遇到了相同的问题，配置都是一样的，经过抓包查看，发现服务器端收到了客户端的流量，但是服务器端将UDP载荷写入tun后数据包消失，而不是预想的通过ens33网卡发送出去

你好，你的linux是哪个发行版本？iptables是否配置了其他丢包策略？

**Comment by JayKuin** [comment]
> 
你好，我的linux 版本是18.04，服务器端iptables规则应该是正确的。
我详细描述下遇到的问题：

我在客户端执行非全局模式，使用以下命令：ping baidu.com -I tun0，服务器端收到该udp包并且成功通过tun发送出去了，收到响应后将icmp响应发回了客户端，但是客户端ping命令并没有收到应答，显示100%丢包率。

在客户端执行全局模式，流量发送到服务器端后，将载荷写入tun设备，抓包未看到ens33网卡收到这些数据包，服务器没有将客户端的原始数据流量发送出去

**Comment by net-byte** [comment]
> > 
> 
> 你好，我的linux 版本是18.04，服务器端iptables规则应该是正确的。 我详细描述下遇到的问题：
> 
> 我在客户端执行非全局模式，使用以下命令：ping baidu.com -I tun0，服务器端收到该udp包并且成功通过tun发送出去了，收到响应后将icmp响应发回了客户端，但是客户端ping命令并没有收到应答，显示100%丢包率。
> 
> 在客户端执行全局模式，流量发送到服务器端后，将载荷写入tun设备，抓包未看到ens33网卡收到这些数据包，服务器没有将客户端的原始数据流量发送出去

之前的nat转发配置有点问题，改成这样试试：
 echo 1 > /proc/sys/net/ipv4/ip_forward
  sysctl -p
  # 设置NAT转发流量
  iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
  iptables -t nat -A POSTROUTING -o tun0 -j MASQUERADE
  iptables -A INPUT -i eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT
  iptables -A INPUT -i tun0 -m state --state RELATED,ESTABLISHED -j ACCEPT
  iptables -A FORWARD -j ACCEPT
