### ISSUE TITLE
How to make sure tcpconn reads a full packet?

### ISSUE THREAD

**Issue by AZLisme** [net-byte/vtun#7]
https://github.com/net-byte/vtun/blob/e115d8d0b6c355d2327da13159b8e141efd7ebf3/tcp/tcpclient.go#L63

As far as I know, TCP is a stream based protocol, even if server side writes a full packet in one write call, there are chance that the packet is divided into mulitple reads. On the other hand, a single read may got multiple packets if it's way samll than MTU, which is 1500.

Is this a issue? Please tell me if I'm wrong.

**Comment by net-byte** [comment]
See the line 67:
b := buffer[:n]
n is the size of packet

**Comment by AZLisme** [comment]
I don't think this is the answer to my question, n is the bytes length you got in a single tcp read. I don't see how it is ensured to be the size of packet.

Let's say you have 2 packet, each 100bytes. Your buffer slice length is 1500, 
after line 63, you may got
n = 200, err = nil
or even worse
n = 150, err = nil,

Is that ok for iface to write in line 74?

**Comment by net-byte** [comment]
You don't need to know the specific packet size, just forward the data in a for loop.
