### ISSUE TITLE
支持参数配置化么

### ISSUE THREAD

**Issue by clywm520** [net-byte/vtun#77]
目前都是命令行参数。 ps -ef 能查看到执行参数，能支持参数配置化么

**Comment by song940** [comment]
Command-line flag `-f` is supported while https://github.com/net-byte/vtun/pull/84 merged, here is an example [config](https://github.com/net-byte/vtun/blob/master/config.json) file.
And more config key name list in [config.go](https://github.com/net-byte/vtun/blob/master/common/config/config.go#L10-L35). 

Feel free to use it, If you have any questions, please let me known.
