### ISSUE TITLE
Invalid server/key

### ISSUE THREAD

**Issue by malikshi** [net-byte/vtun#8]
Sir i running nginx 443 with http2, then create reverse proxy to vtun port. I running vtun with default key 123456 and address tun 172.16.254.1/24. Then try setting up the client on android apps always says invalid server/key
About reverse proxy i used the path /way-to-freedom

**Comment by malikshi** [comment]
Solved.... But still wanto ask questions about the path. Did vtun support path setting?

**Comment by net-byte** [comment]
It is not supported yet, I will consider adding it later.

**Comment by malikshi** [comment]
> It is not supported yet, I will consider adding it later.

I saw this https://github.com/net-byte/vtun/blob/5020240d90e601fd43147b1aff8e01b9ca2634a2/common/netutil/netutil.go#L54
That's why I'm asked support path or not. Thank you for great app.

**Comment by malikshi** [comment]
@net-byte thanks you for the update, https://github.com/net-byte/vtun/commit/a66c371f08da6d738310a3d03387d5702e73d720
however how to compiled fro linux-amd64.

**Comment by net-byte** [comment]
I released the app v1.5.0,https://github.com/net-byte/vTunnel/releases/tag/v1.5.0

**Comment by malikshi** [comment]
configured 
```conf
location /way-to-freedom {
    proxy_pass http://127.0.0.1:3001;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
}```
somehow in android still says invalid key/server

**Comment by malikshi** [comment]
> configured
> 
> ```
> location /way-to-freedom {
>     proxy_pass http://127.0.0.1:3001;
>     proxy_http_version 1.1;
>     proxy_set_header Upgrade $http_upgrade;
>     proxy_set_header Connection "Upgrade";
>     proxy_set_header Host $host;
> }
> ```
> 
> somehow in android still says invalid key/server

i set vtun running like this
`/usr/local/bin/vtun -S -l=:3001 -c=172.16.254.1/24 -k=123456 -p=ws -path=/way-to-freedom`
and nginx reverse like those above. but seem failed to connected to internet/no internet access

but if i set reverse proxy on nginx under path `location /` worked

**Comment by net-byte** [comment]
proxy_pass http://127.0.0.1:3001/;   end with '/'

**Comment by net-byte** [comment]
location /way-to-freedom/ {
    proxy_pass http://127.0.0.1:3001/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
}

**Comment by malikshi** [comment]
> /usr/local/bin/vtun -S -l=:3001 -c=172.16.254.1/24 -k=123456 -p=ws -path=/way-to-freedom

this is correct right?

**Comment by malikshi** [comment]
> but if i set reverse proxy on nginx under path `location /` worked

set reverse under `/`
```conf
 location / {
    proxy_pass http://127.0.0.1:3001;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
 }```
 
 working.. something wrong the code?

**Comment by net-byte** [comment]
The code is right,for easy configuration, I recommend you to use subdomain with location /

**Comment by net-byte** [comment]
The easiest way to configure a reverse proxy is to use caddy2. 

config your Caddyfile:

vpn.your.domain {
    reverse_proxy localhost:3001
}

 1.deploy caddy2 on docker
    docker run -d -p 80:80 -p 443:443 --name caddy --restart=always --net=host -v /data/caddy/Caddyfile:/etc/ caddy/Caddyfile -v /data/caddy/data:/data caddy

2. deploy vtun server on docker
    docker run -d --privileged --restart=always --net=host --name vtun-server netbyte/vtun -S -l=:3001 -c=172.16.0.1/24 -k=123456

**Comment by malikshi** [comment]
> The code is right,for easy configuration, I recommend you to use subdomain with location /

So the one create & redirect the path /way-to-freedom is vtun? I thought set-up nginx with path /way-to-freedom then vtun matched the set with same path as nginx. So i can't use path `/` as dummy sites since its used by vtun?

**Comment by net-byte** [comment]
Thanks for your feedback, and contributions are welcome.
