### ISSUE TITLE
can not build it

### ISSUE THREAD

**Issue by clywm520** [net-byte/vtun#83]
# github.com/net-byte/vtun/tls
tls/tlsclient.go:46:31: cannot use conn (variable of type *"crypto/tls".Conn) as *net.TCPConn value in argument to tcp.Handshake

go verion 1.21

**Comment by song940** [comment]
Faced with same problems, I modify tcpclient.go 

```patch
- func Handshake(config config.Config, conn *net.TCPConn) error {
+ func Handshake(config config.Config, conn net.Conn) error {
	var obj *xproto.ClientHandshakePacket
	var err error
	if v, ok := cache.GetCache().Get(HandshakeTag); ok {
```

It work fine.
