### ISSUE TITLE
failed to dial websocket, first record does not look like a TLS handshake

### ISSUE THREAD

**Issue by seakfind** [net-byte/vtun#9]
The procedure followed on server and client was like this:

**Server**

1. Set up DNS `A` record for server `www.example.com`
2. SSH into server as `root`
3. Install Nginx
4. Install `certbot` and `python3-certbot-nginx`
5. Obtain SSL certificate for Nginx `certbot --nginx -d www.example.com`
6. Download `wget https://github.com/net-byte/vtun/releases/download/v1.4.7/vtun-linux-amd64`
7. Make executable `chmod +x vtun-linux-amd64`
8. `echo 1 > /proc/sys/net/ipv4/ip_forward`
9. `sysctl -p`
10. Masquerade IP address `iptables -t nat -A POSTROUTING -s 172.16.0.0/24 -o ens3 -j MASQUERADE`
11. Run `./vtun-linux-amd64 -S -l=:3001 -c=172.16.0.1/24 -k=szqIOqNMb9Q8IAxm -path "/ycds09kr"`
12. Leave vtun ws server running in terminal

**Client**

1. cd ~/Downloads
2. `wget https://github.com/net-byte/vtun/releases/download/v1.4.7/vtun-linux-amd64`
3. `sudo chmod +x vtun-linux-amd64`
4. `sudo ./vtun-linux-amd64 -l=:3000 -s=www.example.com:3001 -c=172.16.0.10/24 -k=szqIOqNMb9Q8IAxm -path "/ycds09kr"`

**Result**

A message appeared on the client:

`[client] failed to dial websocket wss://www.example.com:3001/ycds09kr tls: first record does not look like a TLS handshake`

**Comment by net-byte** [comment]
Check if the reverse proxy is configured correctly? The reverse proxy needs to configure the websocket protocol

**Comment by net-byte** [comment]
tls: first record does not look like a TLS handshake.
https is not configured correctly

**Comment by seakfind** [comment]
Can you give me an example of a correct configure file?

**Comment by net-byte** [comment]
The easiest way to configure a reverse proxy is to use caddy2.

config your Caddyfile:

vpn.your.domain {
reverse_proxy localhost:3001
}

1.deploy caddy2 on docker
docker run -d -p 80:80 -p 443:443 --name caddy --restart=always --net=host -v /data/caddy/Caddyfile:/etc/ caddy/Caddyfile -v /data/caddy/data:/data caddy

2.deploy vtun server on docker
    docker run -d --privileged --restart=always --net=host --name vtun-server netbyte/vtun -S -l=:3001 -c=172.16.0.1/24 -k=123456
